name: Main

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-3.13-${{ hashFiles('dev-requirements.txt') }}-${{ hashFiles('requirements.txt') }}

      - name: Install Dependencies
        run: pip install -r dev-requirements.txt

      - name: Format
        run: ruff format --check main.py

      - name: Lint
        run: ruff check main.py

  build-deploy:
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/heroku-cloudflare-app-domain:latest
